ENVIRONMENT: 'demo'
FEED: 'OANDA'
ACCOUNT_ID: "101-011-18771552-009"

STRATEGY:
  MODULE: 'simple_macd'
  NAME: 'SimpleMACD'
  INTERVAL: 'H1'
  PERIOD: 300
  RISK_PC: 1.5
  SIZING: 'risk'
  PARAMETERS:
    ema_period: 200
    MACD_fast: 12
    MACD_slow: 26
    MACD_smoothing: 9
    
    # Exit level parameters
    RR: 1.5

WATCHLIST: ['EUR_USD']

BACKTESTING:
  base_currency: 'AUD'
  initial_balance: 1000
  spread: 0.5
  commission: 0.005
  leverage: 30
  FROM: 1/1/2020
  TO: 1/6/2020
