ENVIRONMENT: 'demo'

STRATEGY:
  MODULE: 'modulename'
  NAME: 'StrategyClassName'
  INTERVAL: 'M15'
  PERIOD: 300
  RISK_PC: 1
  SIZING: 'risk'
  PARAMETERS:
    ema_period: 200
    
    # Exit level parameters
    RR: 2

# Define pairs to monitor
WATCHLIST: ['EUR_USD']

BACKTESTING:
  base_currency: 'AUD'
  initial_balance: 1000
  spread: 0.5
  commission: 0.005
  leverage: 30
  FROM: 1/1/2021
  TO: 1/7/2021
